name: Spider Jar Gen CI

on:
  push:
    branches: [ "main", "multiThread" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'jetbrains'
          cache: gradle

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Clean and Build with Gradle
        run: ./gradlew clean app:buildCustomSpiderJar --rerun-tasks

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom_spider_jar
          path: |
            jar/custom_spider.jar
            jar/custom_spider.jar.md5
          retention-days: 30
